// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGOYvjAp21TVzFoND549IhB6-VF05PLAs',
    appId: '1:829373403786:web:056c3dfe10207e99c49373',
    messagingSenderId: '829373403786',
    projectId: 'lemeai-chat-app',
    authDomain: 'lemeai-chat-app.firebaseapp.com',
    storageBucket: 'lemeai-chat-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2M_gWmRRAJDNOtE50OlcVUM57f2SVK6k',
    appId: '1:829373403786:android:beddd62ad29956b8c49373',
    messagingSenderId: '829373403786',
    projectId: 'lemeai-chat-app',
    storageBucket: 'lemeai-chat-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC0PHNgKMnWavD8VQavHqg2cTMB1PJtns',
    appId: '1:829373403786:ios:2d4b8f16997c63a6c49373',
    messagingSenderId: '829373403786',
    projectId: 'lemeai-chat-app',
    storageBucket: 'lemeai-chat-app.firebasestorage.app',
    iosBundleId: 'com.example.lemeaiChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC0PHNgKMnWavD8VQavHqg2cTMB1PJtns',
    appId: '1:829373403786:ios:2d4b8f16997c63a6c49373',
    messagingSenderId: '829373403786',
    projectId: 'lemeai-chat-app',
    storageBucket: 'lemeai-chat-app.firebasestorage.app',
    iosBundleId: 'com.example.lemeaiChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGOYvjAp21TVzFoND549IhB6-VF05PLAs',
    appId: '1:829373403786:web:34cdbd07d65855a3c49373',
    messagingSenderId: '829373403786',
    projectId: 'lemeai-chat-app',
    authDomain: 'lemeai-chat-app.firebaseapp.com',
    storageBucket: 'lemeai-chat-app.firebasestorage.app',
  );
}
